### ISSUE TITLE
sslyze cloudfront problem

### ISSUE THREAD

**Issue by Giannandrea** [nintexplatform/sentinel#42]
I noticed a problem using sslyze test with cloudfront host. 
The problem seems to rely on the command line tool.

```
mauro@c517c4dc9347:/sslyze# sslyze --regular --http_headers pro.beefree.io

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   pro.beefree.io:443                       => ERROR: Connection to server timed out; discarding scan.
``` 
Do you have similar problems in your experience? I'll try to dial with sslyze owner but now use i can fix it.

**Comment by Giannandrea** [comment]
I opened an issue to Sslyze,
https://github.com/nabla-c0d3/sslyze/issues/445
There there are also a couple of workarounds.

**Comment by perryloh-nintex** [comment]
Haven't seen this one since we haven't scanned against any cloudfront sites. If sslyze can fix it then we avoid workarounds.

**Comment by Giannandrea** [comment]
Yeah i agree, i'm going to patch on our installation. I don't think that the fix on sslyze would be so quick.

**Comment by perryloh-nintex** [comment]
Any workarounds available that don't involve a code change in sslyze?

**Comment by Giannandrea** [comment]
no i didn't find any valid workaround outside sslyze because it seems that fails in the connection check.

**Comment by Giannandrea** [comment]
FYI.
SSLyze fixed this problem with a workaround (cit.) in the version v3.0.7.

**Comment by perryloh-nintex** [comment]
That was quick, we should pin and update to v3.0.7.
